In [23]:
import pandas as pd
import numpy as np
import re

In [14]:
# read in data
athlete_bio = pd.read_csv("rawData/archive/Olympic_Athlete_Bio.csv")
athlete_event_results = pd.read_csv("rawData/archive/Olympic_Athlete_Event_Results.csv")
country_medal_count = pd.read_csv("rawData/archive/Olympic_Games_Medal_Tally.csv")
countries = pd.read_csv("rawData/archive/Olympics_Country.csv")

In [21]:
# merge data sets, drop columns
complete_athlete_info = pd.merge(athlete_event_results, athlete_bio, on='athlete_id', how='left')
complete_athlete_info = complete_athlete_info.drop(columns=['country_noc_x', 
                                                            'edition_id',
                                                            'result_id',
                                                            'event',
                                                            'pos',
                                                            'isTeamSport',
                                                            'height',
                                                            'weight',
                                                            'description',
                                                            'special_notes',
                                                            'name'])
complete_athlete_info = complete_athlete_info.rename(columns={'country_noc_y': 'country_noc'})

In [22]:
complete_athlete_info.head()

,edition,sport,athlete,athlete_id,medal,sex,born,country,country_noc
0,1908 Summer Olympics,Athletics,Ernest Hutcheon,64710,NaN,Male,17 June 1889,Australasia,ANZ
1,1908 Summer Olympics,Athletics,Henry Murray,64756,NaN,Male,14 January 1886,Australasia,ANZ
2,1908 Summer Olympics,Athletics,Harvey Sutton,64808,NaN,Male,18 February 1882,Australasia,ANZ
3,1908 Summer Olympics,Athletics,Guy Haskins,922519,NaN,Male,23 December 1883,Australasia,ANZ
4,1908 Summer Olympics,Athletics,Joseph Lynch,64735,NaN,Male,22 April 1878,Australasia,ANZ

In [ ]:
# year column
year_pattern = r'(\d{4})'
complete_athlete_info['year'] = complete_athlete_info['edition'].str.extract(year_pattern)

# season column
season_pattern = r'(Summer|Winter)'
complete_athlete_info['season'] = complete_athlete_info['edition'].str.extract(season_pattern)

In [ ]:
# drop edition column
complete_athlete_info = complete_athlete_info.drop(columns='edition')

In [32]:
complete_athlete_info.head()

,sport,athlete,athlete_id,medal,sex,born,country,country_noc,year,season
0,Athletics,Ernest Hutcheon,64710,NaN,Male,17 June 1889,Australasia,ANZ,1908,Summer
1,Athletics,Henry Murray,64756,NaN,Male,14 January 1886,Australasia,ANZ,1908,Summer
2,Athletics,Harvey Sutton,64808,NaN,Male,18 February 1882,Australasia,ANZ,1908,Summer
3,Athletics,Guy Haskins,922519,NaN,Male,23 December 1883,Australasia,ANZ,1908,Summer
4,Athletics,Joseph Lynch,64735,NaN,Male,22 April 1878,Australasia,ANZ,1908,Summer

In [ ]:
#'rawData/Paris_2024/Paris_2024_Athletes.csv'
#'rawData/Paris_2024/Paris_2024_Medallists.csv'