In [23]:
import pandas as pd
import numpy as np
import re

In [14]:
# read in data
athlete_bio = pd.read_csv("rawData/archive/Olympic_Athlete_Bio.csv")
athlete_event_results = pd.read_csv("rawData/archive/Olympic_Athlete_Event_Results.csv")
country_medal_count = pd.read_csv("rawData/archive/Olympic_Games_Medal_Tally.csv")
countries = pd.read_csv("rawData/archive/Olympics_Country.csv")

In [21]:
# merge data sets, drop columns
complete_athlete_info = pd.merge(athlete_event_results, athlete_bio, on='athlete_id', how='left')
complete_athlete_info = complete_athlete_info.drop(columns=['country_noc_x', 
                                                            'edition_id',
                                                            'result_id',
                                                            'event',
                                                            'pos',
                                                            'isTeamSport',
                                                            'height',
                                                            'weight',
                                                            'description',
                                                            'special_notes',
                                                            'name'])
complete_athlete_info = complete_athlete_info.rename(columns={'country_noc_y': 'country_noc'})

In [22]:
complete_athlete_info.head()

,edition,sport,athlete,athlete_id,medal,sex,born,country,country_noc
0,1908 Summer Olympics,Athletics,Ernest Hutcheon,64710,NaN,Male,17 June 1889,Australasia,ANZ
1,1908 Summer Olympics,Athletics,Henry Murray,64756,NaN,Male,14 January 1886,Australasia,ANZ
2,1908 Summer Olympics,Athletics,Harvey Sutton,64808,NaN,Male,18 February 1882,Australasia,ANZ
3,1908 Summer Olympics,Athletics,Guy Haskins,922519,NaN,Male,23 December 1883,Australasia,ANZ
4,1908 Summer Olympics,Athletics,Joseph Lynch,64735,NaN,Male,22 April 1878,Australasia,ANZ

In [ ]:
# year column
year_pattern = r'(\d{4})'
complete_athlete_info['year'] = complete_athlete_info['edition'].str.extract(year_pattern)

# season column
season_pattern = r'(Summer|Winter)'
complete_athlete_info['season'] = complete_athlete_info['edition'].str.extract(season_pattern)

In [ ]:
# drop edition column
complete_athlete_info = complete_athlete_info.drop(columns='edition')

In [32]:
complete_athlete_info.head()

,sport,athlete,athlete_id,medal,sex,born,country,country_noc,year,season
0,Athletics,Ernest Hutcheon,64710,NaN,Male,17 June 1889,Australasia,ANZ,1908,Summer
1,Athletics,Henry Murray,64756,NaN,Male,14 January 1886,Australasia,ANZ,1908,Summer
2,Athletics,Harvey Sutton,64808,NaN,Male,18 February 1882,Australasia,ANZ,1908,Summer
3,Athletics,Guy Haskins,922519,NaN,Male,23 December 1883,Australasia,ANZ,1908,Summer
4,Athletics,Joseph Lynch,64735,NaN,Male,22 April 1878,Australasia,ANZ,1908,Summer

In [74]:
# read in 2024 data
athletes_2024 = pd.read_csv('rawData/Paris_2024/Paris_2024_Athletes.csv')
medallists_2024 = pd.read_csv('rawData/Paris_2024/Paris_2024_Medallists.csv')

In [75]:
# drop extra columns
medallists_2024 = medallists_2024.drop(columns=['medal_date',
                                       'medal_code',
                                       'nationality_code',
                                       'nationality',
                                       'nationality_long',
                                       'team',
                                       'team_gender',
                                       'event',
                                       'event_type',
                                       'url_event',
                                       'code_team',
                                       'country_long'])

In [76]:
medallists_2024.head()

,medal_type,name,gender,country_code,country,discipline,birth_date,code_athlete,is_medallist
0,Gold Medal,EVENEPOEL Remco,Male,BEL,Belgium,Cycling Road,2000-01-25,1903136,True
1,Silver Medal,GANNA Filippo,Male,ITA,Italy,Cycling Road,1996-07-25,1923520,True
2,Bronze Medal,van AERT Wout,Male,BEL,Belgium,Cycling Road,1994-09-15,1903147,True
3,Gold Medal,BROWN Grace,Female,AUS,Australia,Cycling Road,1992-07-07,1940173,True
4,Silver Medal,HENDERSON Anna,Female,GBR,Great Britain,Cycling Road,1998-11-14,1912525,True

In [78]:
# drop extra columns
athletes_2024 = athletes_2024.drop(columns=['current',
                                            'name_short',
                                            'function',
                                            'country_long',
                                            'nationality',
                                            'nationality_long',
                                            'nationality_code',
                                            'height',
                                            'weight',
                                            'events',
                                            'birth_place',
                                            'birth_country',
                                            'residence_place',
                                            'residence_country',
                                            'nickname',
                                            'hobbies',
                                            'occupation',
                                            'education',
                                            'family',
                                            'lang',
                                            'coach',
                                            'reason',
                                            'hero',
                                            'influence',
                                            'philosophy',
                                            'sporting_relatives',
                                            'ritual',
                                            'other_sports',
                                            'name_tv'])

In [79]:
athletes_2024.head()

,code,name,gender,country_code,country,disciplines,birth_date
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,['Wrestling'],1991-10-21
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,['Wrestling'],1999-01-22
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,['Wrestling'],1996-12-21
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,['Wrestling'],1999-11-22
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,['Wrestling'],1999-10-27

In [85]:
print(medallists_2024.shape[0])
print(athletes_2024.shape[0])

2315
11113

In [88]:
joined_2024 = pd.merge(athletes_2024, medallists_2024, 
                       left_on='code',
                        right_on='code_athlete',
                        how='left')

In [89]:
print(joined_2024.shape[0])

11374

In [90]:
joined_2024.head()

,code,name_x,gender_x,country_code_x,country_x,disciplines,birth_date_x,medal_type,name_y,gender_y,country_code_y,country_y,discipline,birth_date_y,code_athlete,is_medallist
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,['Wrestling'],1991-10-21,Silver Medal,ALEKSANYAN Artur,Male,ARM,Armenia,Wrestling,1991-10-21,1532872.0,True
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,['Wrestling'],1999-01-22,Bronze Medal,AMOYAN Malkhas,Male,ARM,Armenia,Wrestling,1999-01-22,1532873.0,True
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,['Wrestling'],1996-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,['Wrestling'],1999-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,['Wrestling'],1999-10-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN