In [122]:
# Load necessary libraries
import pandas as pd
import numpy as np

In [123]:
# Read in data
world_indicators = pd.read_csv("rawData/World_Development_Indicator/Indicator_Data_1960-2023.csv")
country_medals = pd.read_csv("rawData/Sum_Win_Olympics_1896-2022/Olympic_Games_Medal_Tally.csv")

In [124]:
# Drop unnecessary column
world_indicators = world_indicators.drop(columns=['Series Code'])

# Drop regions and keep countries only
world_indicators = world_indicators[:1519]

# Fill missing values
world_indicators = world_indicators.replace('..', np.nan)

In [125]:
world_indicators.tail()

,Country Name,Country Code,Series Name,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],1966 [YR1966],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
1514,Zimbabwe,ZWE,Adjusted savings: education expenditure (curre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,330438255.593,336253198.641,343849512.357,297840720.256792,638759370.41362,410417676.08557,401703465.437254,528539985.990914,NaN,NaN
1515,Zimbabwe,ZWE,Current health expenditure per capita (current...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,114.44429779,105.09803009,106.18969727,92.25428772,114.63294983,54.80850601,50.67650986,62.73724365,NaN,NaN
1516,Zimbabwe,ZWE,Human capital index (HCI) (scale 0-1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.441,0.461241573095322,NaN,0.46689310669899,NaN,NaN,NaN
1517,Zimbabwe,ZWE,"Life expectancy at birth, total (years)",53.235,53.619,54.071,54.549,54.994,55.459,55.889,...,58.846,59.591,60.306,60.709,61.414,61.292,61.124,59.253,59.391,NaN
1518,Zimbabwe,ZWE,"Population, total",3809389,3930401,4055959,4185877,4320006,4458462,4601217,...,14207359,14399013,14600294,14812482,15034452,15271368,15526888,15797210,16069056,16340822

In [126]:
# Get number of countries
len(world_indicators['Country Name'].unique().tolist())

217

In [127]:
# Convert year columns into rows
world_indicators = world_indicators.melt(id_vars=['Country Name', 'Country Code', 'Series Name'], var_name='Year')

world_indicators['value'] = pd.to_numeric(world_indicators['value'], errors='coerce')

world_indicators.head(20)

,Country Name,Country Code,Series Name,Year,value
0,Afghanistan,AFG,GDP per capita (current US$),1960 [YR1960],NaN
1,Afghanistan,AFG,GDP (current US$),1960 [YR1960],NaN
2,Afghanistan,AFG,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
3,Afghanistan,AFG,Current health expenditure per capita (current...,1960 [YR1960],NaN
4,Afghanistan,AFG,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
5,Afghanistan,AFG,"Life expectancy at birth, total (years)",1960 [YR1960],3.253500e+01
6,Afghanistan,AFG,"Population, total",1960 [YR1960],9.035043e+06
7,Albania,ALB,GDP per capita (current US$),1960 [YR1960],NaN
8,Albania,ALB,GDP (current US$),1960 [YR1960],NaN
9,Albania,ALB,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
10,Albania,ALB,Current health expenditure per capita (current...,1960 [YR1960],NaN
11,Albania,ALB,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
12,Albania,ALB,"Life expectancy at birth, total (years)",1960 [YR1960],5.443900e+01
13,Albania,ALB,"Population, total",1960 [YR1960],1.608800e+06
14,Algeria,DZA,GDP per capita (current US$),1960 [YR1960],2.383925e+02
15,Algeria,DZA,GDP (current US$),1960 [YR1960],2.723615e+09
16,Algeria,DZA,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
17,Algeria,DZA,Current health expenditure per capita (current...,1960 [YR1960],NaN
18,Algeria,DZA,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
19,Algeria,DZA,"Life expectancy at birth, total (years)",1960 [YR1960],4.053200e+01

In [128]:
# Convert series name rows into columns
world_indicators = world_indicators.pivot_table(index=['Country Name', 'Country Code', 'Year'], columns='Series Name', values='value').reset_index().rename_axis(columns=None)

world_indicators.head(20)

,Country Name,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,Afghanistan,AFG,1960 [YR1960],NaN,NaN,NaN,NaN,NaN,32.535,9035043.0
1,Afghanistan,AFG,1961 [YR1961],NaN,NaN,NaN,NaN,NaN,33.068,9214083.0
2,Afghanistan,AFG,1962 [YR1962],NaN,NaN,NaN,NaN,NaN,33.547,9404406.0
3,Afghanistan,AFG,1963 [YR1963],NaN,NaN,NaN,NaN,NaN,34.016,9604487.0
4,Afghanistan,AFG,1964 [YR1964],NaN,NaN,NaN,NaN,NaN,34.494,9814318.0
5,Afghanistan,AFG,1965 [YR1965],NaN,NaN,NaN,NaN,NaN,34.953,10036008.0
6,Afghanistan,AFG,1966 [YR1966],NaN,NaN,NaN,NaN,NaN,35.453,10266395.0
7,Afghanistan,AFG,1967 [YR1967],NaN,NaN,NaN,NaN,NaN,35.924,10505959.0
8,Afghanistan,AFG,1968 [YR1968],NaN,NaN,NaN,NaN,NaN,36.418,10756922.0
9,Afghanistan,AFG,1969 [YR1969],NaN,NaN,NaN,NaN,NaN,36.910,11017409.0
10,Afghanistan,AFG,1970 [YR1970],1.816169e+07,NaN,NaN,NaN,NaN,37.418,11290128.0
11,Afghanistan,AFG,1971 [YR1971],1.868887e+07,NaN,NaN,NaN,NaN,37.923,11567667.0
12,Afghanistan,AFG,1972 [YR1972],1.631109e+07,NaN,NaN,NaN,NaN,38.444,11853696.0
13,Afghanistan,AFG,1973 [YR1973],2.302442e+07,NaN,NaN,NaN,NaN,39.003,12157999.0
14,Afghanistan,AFG,1974 [YR1974],3.340536e+07,NaN,NaN,NaN,NaN,39.550,12469127.0
15,Afghanistan,AFG,1975 [YR1975],2.901333e+07,NaN,NaN,NaN,NaN,40.100,12773954.0
16,Afghanistan,AFG,1976 [YR1976],3.960777e+07,NaN,NaN,NaN,NaN,40.645,13059851.0
17,Afghanistan,AFG,1977 [YR1977],4.224889e+07,NaN,NaN,NaN,NaN,41.228,13340756.0
18,Afghanistan,AFG,1978 [YR1978],5.113616e+07,NaN,NaN,NaN,NaN,40.271,13611441.0
19,Afghanistan,AFG,1979 [YR1979],5.286041e+07,NaN,NaN,NaN,NaN,39.086,13655567.0

In [129]:
# Clean year column
world_indicators['Year'] = world_indicators['Year'].str.extract(r'(\d{4})').astype(int)

world_indicators.head()

,Country Name,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,Afghanistan,AFG,1960,NaN,NaN,NaN,NaN,NaN,32.535,9035043.0
1,Afghanistan,AFG,1961,NaN,NaN,NaN,NaN,NaN,33.068,9214083.0
2,Afghanistan,AFG,1962,NaN,NaN,NaN,NaN,NaN,33.547,9404406.0
3,Afghanistan,AFG,1963,NaN,NaN,NaN,NaN,NaN,34.016,9604487.0
4,Afghanistan,AFG,1964,NaN,NaN,NaN,NaN,NaN,34.494,9814318.0

In [130]:
print(country_medals.shape)
print(world_indicators.shape)

(1807, 9)
(13858, 10)

In [131]:
# Extract season column
season_pattern = r'(Summer|Winter|Equestrian|Intercalated)'
country_medals['season'] = country_medals['edition'].str.extract(season_pattern)

# Drop extra columns
country_medals = country_medals.drop(columns=['edition',
                                              'edition_id'])

country_medals.head()

country_medals.to_csv('country_medals.csv', index=False)

In [132]:
# Convert to types
country_medals['country_noc'] = country_medals['country_noc'].astype(str)
world_indicators['Country Code'] = world_indicators['Country Code'].astype(str)

country_medals['country_noc'] = country_medals['country_noc'].str.strip()
world_indicators['Country Code'] = world_indicators['Country Code'].str.strip()

country_medals['year'] = country_medals['year'].astype(int)
world_indicators['Year'] = world_indicators['Year'].astype(int)

In [133]:
# Get a list of unmatched country codes used for the same countries
country_medal_codes = country_medals['country_noc'].unique().tolist()

world_indicator_codes = world_indicators['Country Code'].unique().tolist()

unmatched_codes = list(set(country_medal_codes) - set(world_indicator_codes))

print(unmatched_codes)
print(len(unmatched_codes))

['UAR', 'INA', 'NED', 'ROC', 'SUD', 'BOT', 'CRC', 'BER', 'CRO', 'ISV', 'PUR', 'GDR', 'TOG', 'HAI', 'MGL', 'RSA', 'TAN', 'URS', 'NIG', 'GUA', 'POR', 'ALG', 'BUL', 'SAM', 'SRI', 'URU', 'IRI', 'UAE', 'TCH', 'KOS', 'SLO', 'LAT', 'KSA', 'NGR', 'BAH', 'KUW', 'YUG', 'EUN', 'AHO', 'BUR', 'ZAM', 'IOA', 'SCG', 'FIJ', 'TGA', 'VIE', 'TPE', 'BOH', 'DEN', 'PHI', 'GER', 'SUI', 'MAS', 'MRI', 'ZIM', 'GRN', 'WIF', 'MIX', 'PAR', 'ANZ', 'MON', 'FRG', 'GRE', 'BAR']
64

In [134]:
# Create code dictionary 
code_dict = {
    'DZA':'ALG',
    'BHS':'BAH',
    'BRB':'BAR',
    'BMU':'BER',
    'BWA':'BOT',
    'BGR':'BUL',
    'BFA':'BUR',
    'CRI':'CRC',
    'HRV':'CRO',
    'DNK':'DEN',
    'FJI':'FIJ',
    'DEU':'GER',
    'GRC':'GRE',
    'GRD':'GRN',
    'GTM':'GUA',
    'HTI':'HAI',
    'IDN':'INA',
    'IRN':'IRI',
    'VIR':'ISV',
    'XKX':'KOS',
    'SAU':'KSA',
    'KWT':'KUW',
    'LVA':'LAT',
    'MYS':'MAS',
    'MNG':'MGL',
    'MCO':'MON',
    'MUS':'MRI',
    'NLD':'NED',
    'NGA':'NGR',
    'NER':'NIG',
    'PRY':'PAR',
    'PHL':'PHI',
    'PRT':'POR',
    'PRI':'PUR',
    'ZAF':'RSA',
    'ASM':'SAM',
    'SVN':'SLO',
    'LKA':'SRI',
    'SSD':'SUD',
    'CHE':'SUI',
    'TZA':'TAN',
    'TON':'TGA',
    'TGO':'TOG',
    'ARE':'UAE',
    'URY':'URU',
    'VNM':'VIE',
    'ZMB':'ZAM',
    'ZWE':'ZIM'
}

print(len(code_dict))

48

In [135]:
# Replace only the matching values and keep all unmachted values unchanged
world_indicators['Country Code'] = world_indicators['Country Code'].replace(code_dict)

In [136]:
# Get a list of unmatched country codes used for the same countries
country_medal_codes = country_medals['country_noc'].unique().tolist()

world_indicator_codes = world_indicators['Country Code'].unique().tolist()

unmatched_codes = list(set(country_medal_codes) - set(world_indicator_codes))

print(unmatched_codes)
print(len(unmatched_codes))

['YUG', 'UAR', 'EUN', 'URS', 'ROC', 'AHO', 'IOA', 'SCG', 'TPE', 'BOH', 'WIF', 'MIX', 'ANZ', 'TCH', 'FRG', 'GDR']
16

In [137]:
# Merge datasets
final_medal_indicator_dataset = pd.merge(
    country_medals,
    world_indicators,
    left_on=['country_noc', 'year'],
    right_on=['Country Code', 'Year'],
    how='left'
)

print(final_medal_indicator_dataset.shape[0])

1807

In [138]:
# Get a list of unmatched country codes used for the same countries
country_medal_codes = country_medals['country_noc'].unique().tolist()

final_medal_indicator_data_codes = final_medal_indicator_dataset['Country Code'].unique().tolist()

unmatched_codes = list(set(country_medal_codes) - set(final_medal_indicator_data_codes))

print(unmatched_codes)
print(len(unmatched_codes))

['YUG', 'UAR', 'EUN', 'URS', 'ROC', 'AHO', 'IOA', 'SCG', 'TPE', 'BOH', 'WIF', 'MIX', 'ANZ', 'TCH', 'MON', 'FRG', 'GDR', 'HAI']
18

In [139]:
# Drop extra columns
final_medal_indicator_dataset = final_medal_indicator_dataset.drop(columns=['Year',
                                                                            'Country Code',
                                                                            'Country Name'])

# Rename columns
final_medal_indicator_dataset = final_medal_indicator_dataset.rename(columns={'year': 'Year',
                                                                              'season': 'Season',
                                                                              'country': 'Country',
                                                                              'country_noc': 'Country Code',
                                                                              'gold': 'Gold',
                                                                              'silver': 'Silver',
                                                                              'bronze': 'Bronze',
                                                                              'total': 'Total',
                                                                              'GDP per capita (current US$)': 'GDP Per Capita (current US$)',
                                                                              'Population, total': 'Total Population',
                                                                              'Life expectancy at birth, total (years)': 'Life Expectancy At Birth (years)',
                                                                              'Adjusted savings: education expenditure (current US$)': 'Education Expenditure (current US$)',
                                                                              'Current health expenditure per capita (current US$)': 'Health Expenditure Per Capita (current US$)',
                                                                              'Human capital index (HCI) (scale 0-1)': 'Human Capital Index (HCI) (scale 0-1)'})

# Reoder columns
final_medal_indicator_dataset = final_medal_indicator_dataset[['Year',
                                                               'Season',
                                                               'Country',
                                                               'Country Code',
                                                               'Gold',
                                                               'Silver',
                                                               'Bronze',
                                                               'Total',
                                                               'GDP (current US$)',
                                                               'GDP Per Capita (current US$)',
                                                               'Total Population',
                                                               'Life Expectancy At Birth (years)',
                                                               'Education Expenditure (current US$)',
                                                               'Health Expenditure Per Capita (current US$)',
                                                               'Human Capital Index (HCI) (scale 0-1)']]

In [140]:
final_medal_indicator_dataset.to_csv('final_medal_indicator_dataset.csv', index=False)