In [ ]:
# merge with country_medal_count on country code

In [1]:
import pandas as pd
import numpy as np

In [40]:
world_indicators = pd.read_csv("World_Development_Indicator/Indicator_Data_1960-2023.csv")

In [21]:
world_indicators.head()

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,..,..,..,..,..,..,...,625.054941813938,565.569730408751,522.082215583898,525.469770891619,491.337221382603,496.6025042585,510.787063366811,356.496214115892,357.261152798144,415.707417059086
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,..,..,..,..,..,..,...,20497128555.6972,19134221644.7325,18116572395.0772,18753456497.8159,18053222687.4126,18799444490.1128,19955929052.1496,14259995441.0759,14497243872.1337,17233051620.1117
2,Afghanistan,AFG,Adjusted savings: education expenditure (curre...,NY.ADJ.AEDU.CD,..,..,..,..,..,..,...,612803653.538383,523532102.941459,472166739.725436,496707377.967453,482833320.042869,498263992.940825,527512991.719678,386856048.870212,..,..
3,Afghanistan,AFG,Current health expenditure per capita (current...,SH.XPD.CHEX.PC.CD,..,..,..,..,..,..,...,60.18957901,60.05854034,61.48645782,66.90921783,71.33430481,74.23410797,80.28805542,81.31976318,..,..
4,Afghanistan,AFG,Human capital index (HCI) (scale 0-1),HD.HCI.OVRL,..,..,..,..,..,..,...,..,..,..,0.389,0.393489241600037,..,0.400284141302109,..,..,..

In [41]:
# drop column
world_indicators = world_indicators.drop(columns=['Series Code', 'Country Name'])
# drop regions
world_indicators = world_indicators[:1519]

In [61]:
world_indicators = world_indicators.replace('..', np.nan)
world_indicators.head()

,Country Code,Series Name,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],1966 [YR1966],1967 [YR1967],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,AFG,GDP per capita (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,625.054941813938,565.569730408751,522.082215583898,525.469770891619,491.337221382603,496.6025042585,510.787063366811,356.496214115892,357.261152798144,415.707417059086
1,AFG,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20497128555.6972,19134221644.7325,18116572395.0772,18753456497.8159,18053222687.4126,18799444490.1128,19955929052.1496,14259995441.0759,14497243872.1337,17233051620.1117
2,AFG,Adjusted savings: education expenditure (curre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,612803653.538383,523532102.941459,472166739.725436,496707377.967453,482833320.042869,498263992.940825,527512991.719678,386856048.870212,NaN,NaN
3,AFG,Current health expenditure per capita (current...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.18957901,60.05854034,61.48645782,66.90921783,71.33430481,74.23410797,80.28805542,81.31976318,NaN,NaN
4,AFG,Human capital index (HCI) (scale 0-1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.389,0.393489241600037,NaN,0.400284141302109,NaN,NaN,NaN

In [67]:
world_indicators = world_indicators.melt(id_vars=['Country Code', 'Series Name'], var_name='Year')
world_indicators['value'] = pd.to_numeric(world_indicators['value'], errors='coerce')
world_indicators.head(20)

,Country Code,Series Name,Year,value
0,AFG,GDP per capita (current US$),1960 [YR1960],NaN
1,AFG,GDP (current US$),1960 [YR1960],NaN
2,AFG,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
3,AFG,Current health expenditure per capita (current...,1960 [YR1960],NaN
4,AFG,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
5,AFG,"Life expectancy at birth, total (years)",1960 [YR1960],3.253500e+01
6,AFG,"Population, total",1960 [YR1960],9.035043e+06
7,ALB,GDP per capita (current US$),1960 [YR1960],NaN
8,ALB,GDP (current US$),1960 [YR1960],NaN
9,ALB,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
10,ALB,Current health expenditure per capita (current...,1960 [YR1960],NaN
11,ALB,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
12,ALB,"Life expectancy at birth, total (years)",1960 [YR1960],5.443900e+01
13,ALB,"Population, total",1960 [YR1960],1.608800e+06
14,DZA,GDP per capita (current US$),1960 [YR1960],2.383925e+02
15,DZA,GDP (current US$),1960 [YR1960],2.723615e+09
16,DZA,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
17,DZA,Current health expenditure per capita (current...,1960 [YR1960],NaN
18,DZA,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
19,DZA,"Life expectancy at birth, total (years)",1960 [YR1960],4.053200e+01

In [68]:
world_indicators = world_indicators.pivot_table(index=['Country Code', 'Year'], columns='Series Name', values='value')
world_indicators.head(10)

Series Name                 Adjusted savings: education expenditure (current US$)  \
Country Code Year
ABW          1960 [YR1960]                                                NaN
             1961 [YR1961]                                                NaN
             1962 [YR1962]                                                NaN
             1963 [YR1963]                                                NaN
             1964 [YR1964]                                                NaN
             1965 [YR1965]                                                NaN
             1966 [YR1966]                                                NaN
             1967 [YR1967]                                                NaN
             1968 [YR1968]                                                NaN
             1969 [YR1969]                                                NaN

Series Name                 Current health expenditure per capita (current US$)  \
Country Code Year
ABW          1960 [YR1960]                                                NaN
             1961 [YR1961]                                                NaN
             1962 [YR1962]                                                NaN
             1963 [YR1963]                                                NaN
             1964 [YR1964]                                                NaN
             1965 [YR1965]                                                NaN
             1966 [YR1966]                                                NaN
             1967 [YR1967]                                                NaN
             1968 [YR1968]                                                NaN
             1969 [YR1969]                                                NaN

Series Name                 GDP (current US$)  GDP per capita (current US$)  \
Country Code Year
ABW          1960 [YR1960]                NaN                           NaN
             1961 [YR1961]                NaN                           NaN
             1962 [YR1962]                NaN                           NaN
             1963 [YR1963]                NaN                           NaN
             1964 [YR1964]                NaN                           NaN
             1965 [YR1965]                NaN                           NaN
             1966 [YR1966]                NaN                           NaN
             1967 [YR1967]                NaN                           NaN
             1968 [YR1968]                NaN                           NaN
             1969 [YR1969]                NaN                           NaN

Series Name                 Human capital index (HCI) (scale 0-1)  \
Country Code Year
ABW          1960 [YR1960]                                    NaN
             1961 [YR1961]                                    NaN
             1962 [YR1962]                                    NaN
             1963 [YR1963]                                    NaN
             1964 [YR1964]                                    NaN
             1965 [YR1965]                                    NaN
             1966 [YR1966]                                    NaN
             1967 [YR1967]                                    NaN
             1968 [YR1968]                                    NaN
             1969 [YR1969]                                    NaN

Series Name                 Life expectancy at birth, total (years)  \
Country Code Year
ABW          1960 [YR1960]                                   64.152
             1961 [YR1961]                                   64.537
             1962 [YR1962]                                   64.752
             1963 [YR1963]                                   65.132
             1964 [YR1964]                                   65.294
             1965 [YR1965]                                   65.502
             1966 [YR1966]                                   66.063
             1967 [YR1967]                                   66.439
             1968 [YR1968]                                   66.757
             1969 [YR1969]                                   67.168

Series Name                 Population, total
Country Code Year
ABW          1960 [YR1960]            54922.0
             1961 [YR1961]            55578.0
             1962 [YR1962]            56320.0
             1963 [YR1963]            57002.0
             1964 [YR1964]            57619.0
             1965 [YR1965]            58190.0
             1966 [YR1966]            58694.0
             1967 [YR1967]            58990.0
             1968 [YR1968]            59069.0
             1969 [YR1969]            59052.0

In [69]:
world_indicators = world_indicators.reset_index().rename_axis(columns=None)
world_indicators.head()

,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,ABW,1960 [YR1960],NaN,NaN,NaN,NaN,NaN,64.152,54922.0
1,ABW,1961 [YR1961],NaN,NaN,NaN,NaN,NaN,64.537,55578.0
2,ABW,1962 [YR1962],NaN,NaN,NaN,NaN,NaN,64.752,56320.0
3,ABW,1963 [YR1963],NaN,NaN,NaN,NaN,NaN,65.132,57002.0
4,ABW,1964 [YR1964],NaN,NaN,NaN,NaN,NaN,65.294,57619.0

In [72]:
world_indicators['Year'] = world_indicators['Year'].str.extract(r'(\d{4})').astype(int)
world_indicators.head()

,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,ABW,1960,NaN,NaN,NaN,NaN,NaN,64.152,54922.0
1,ABW,1961,NaN,NaN,NaN,NaN,NaN,64.537,55578.0
2,ABW,1962,NaN,NaN,NaN,NaN,NaN,64.752,56320.0
3,ABW,1963,NaN,NaN,NaN,NaN,NaN,65.132,57002.0
4,ABW,1964,NaN,NaN,NaN,NaN,NaN,65.294,57619.0